/**
 * VibeLux Browser Polyfills
 * Auto-generated by polyfill-check.js
 * 
 * This file ensures compatibility with older browsers
 */

// Core JavaScript polyfills
import 'core-js/stable';
import 'regenerator-runtime/runtime';

// DOM API polyfills
if (typeof window !== 'undefined') {
  // IntersectionObserver for lazy loading
  if (!window.IntersectionObserver) {
    require('intersection-observer');
  }
  
  // ResizeObserver for responsive components
  if (!window.ResizeObserver) {
    const { ResizeObserver } = require('@juggle/resize-observer');
    window.ResizeObserver = ResizeObserver;
  }
  
  // Smooth scrolling
  if (!('scrollBehavior' in document.documentElement.style)) {
    require('smoothscroll-polyfill').polyfill();
  }
  
  // RequestAnimationFrame
  if (!window.requestAnimationFrame) {
    require('raf').polyfill();
  }
  
  // Fetch API
  if (!window.fetch) {
    require('whatwg-fetch');
  }
  
  // URLSearchParams
  if (!window.URLSearchParams) {
    require('url-search-params-polyfill');
  }
  
  // Custom Event
  if (typeof window.CustomEvent !== 'function') {
    function CustomEvent(event, params) {
      params = params || { bubbles: false, cancelable: false, detail: null };
      const evt = document.createEvent('CustomEvent');
      evt.initCustomEvent(event, params.bubbles, params.cancelable, params.detail);
      return evt;
    }
    window.CustomEvent = CustomEvent;
  }
  
  // WebGL check for Forge viewer
  const canvas = document.createElement('canvas');
  const gl = canvas.getContext('webgl') || canvas.getContext('experimental-webgl');
  if (!gl) {
    console.error('WebGL not supported! Forge viewer will not work.');
    // Show fallback UI
    if (document.body) {
      const warning = document.createElement('div');
      warning.style.cssText = `
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        background: #ff6b6b;
        color: white;
        padding: 10px;
        text-align: center;
        z-index: 9999;
      `;
      warning.textContent = 'WebGL is not supported in your browser. 3D features will not work.';
      document.body.appendChild(warning);
    }
  }
}

// THREE.js specific polyfills
if (typeof window !== 'undefined' && window.THREE) {
  // Polyfill for CSS2DRenderer if not available
  if (!window.CSS2DRenderer && window.THREE.CSS2DRenderer) {
    window.CSS2DRenderer = window.THREE.CSS2DRenderer;
  }
  if (!window.CSS2DObject && window.THREE.CSS2DObject) {
    window.CSS2DObject = window.THREE.CSS2DObject;
  }
}

// Autodesk Forge specific checks
if (typeof window !== 'undefined') {
  // Wait for Forge viewer to be available
  const checkForgeViewer = () => {
    if (window.Autodesk && window.Autodesk.Viewing) {
      console.log('Forge Viewer detected');
      
      // Add any Forge-specific polyfills here
      if (!window.Autodesk.Viewing.Private) {
        window.Autodesk.Viewing.Private = {};
      }
    } else {
      // Retry after a short delay
      setTimeout(checkForgeViewer, 100);
    }
  };
  
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', checkForgeViewer);
  } else {
    checkForgeViewer();
  }
}

// Performance polyfills
if (typeof window !== 'undefined') {
  // Performance.now()
  if (!window.performance || !window.performance.now) {
    window.performance = window.performance || {};
    window.performance.now = function() {
      return Date.now();
    };
  }
  
  // High resolution timestamps
  if (!window.performance.mark) {
    window.performance.mark = function() {};
  }
  if (!window.performance.measure) {
    window.performance.measure = function() {};
  }
}

console.log('VibeLux polyfills loaded');
