/**
 * Revenue Sharing Terms & Conditions
 * Legal agreement for VibeLux Energy Savings Program
 */

export const REVENUE_SHARING_AGREEMENT = {
  version: '2.0',
  effectiveDate: '2024-01-01',
  lastUpdated: '2024-01-20',
  
  title: 'VibeLux Energy Savings Revenue Sharing Agreement',
  
  parties: {
    provider: {
      name: 'VibeLux AI, Inc.',
      type: 'Service Provider',
      address: '1234 Innovation Drive, San Francisco, CA 94105'
    },
    customer: {
      name: '[Customer Name]',
      type: 'Customer',
      address: '[Customer Address]'
    }
  },
  
  terms: {
    1: {
      title: 'REVENUE SHARING MODEL',
      content: `
        1.1 The Customer agrees to share thirty percent (30%) of verified energy savings with VibeLux as compensation for the Energy Optimization Services.
        
        1.2 Energy savings are calculated as the difference between:
            a) Weather-normalized baseline consumption (established from 12 months historical data)
            b) Actual consumption during the service period
        
        1.3 The Customer retains seventy percent (70%) of all verified savings.
        
        1.4 Revenue sharing applies to:
            a) Direct energy cost savings (kWh reduction)
            b) Demand charge reductions (kW reduction)
            c) Demand response program revenues
            d) Utility rebates and incentives earned through the platform
        
        1.5 NO UPFRONT COSTS: Customer pays nothing unless savings are generated.
      `
    },
    
    2: {
      title: 'PAYMENT AUTHORIZATION',
      content: `
        2.1 AUTOMATIC PAYMENT AUTHORIZATION: By accepting these terms, Customer expressly authorizes VibeLux to:
            a) Automatically charge the designated payment method for VibeLux's revenue share
            b) Process payments via ACH transfer, credit card, or wire transfer
            c) Initiate payment collection on the 15th of each month
            d) Retry failed payments up to 3 times within 30 days
        
        2.2 PAYMENT METHOD: Customer agrees to maintain a valid payment method on file:
            a) Primary: ACH/Bank Transfer (preferred - no processing fees)
            b) Secondary: Credit/Debit Card (2.9% processing fee may apply)
            c) Enterprise: Wire Transfer or Check (NET 30 terms)
        
        2.3 Customer grants VibeLux permission to:
            a) Store payment information securely
            b) Update payment methods as needed
            c) Process recurring monthly charges
            d) Adjust payment amounts based on actual verified savings
      `
    },
    
    3: {
      title: 'UTILITY DATA ACCESS',
      content: `
        3.1 Customer authorizes VibeLux to:
            a) Access utility account data via API or Green Button Connect
            b) Receive and process utility bills (PDF, email, or manual upload)
            c) Connect to utility demand response programs on Customer's behalf
            d) Submit meter data for verification and settlement
        
        3.2 Data Access Methods:
            a) Automated API connection (preferred)
            b) Email forwarding of utility bills to bills@vibelux.ai
            c) Manual upload via customer portal
            d) OCR processing of scanned bills
        
        3.3 Customer agrees to:
            a) Provide utility account credentials for API access
            b) Maintain active utility data sharing authorization
            c) Promptly upload or forward monthly utility bills
            d) Notify VibeLux of any account changes
      `
    },
    
    4: {
      title: 'SAVINGS CALCULATION & VERIFICATION',
      content: `
        4.1 Baseline Establishment:
            a) 12 months of historical data required
            b) Weather normalization applied using NOAA data
            c) Adjustments for facility changes or expansions
            d) Annual baseline review and adjustment
        
        4.2 Savings Verification:
            a) Monthly automated calculation
            b) Third-party verification available upon request
            c) Weather normalization using degree-day analysis
            d) Dispute resolution within 30 days
        
        4.3 Performance Guarantee:
            a) Minimum 15% energy savings guaranteed
            b) No charges if savings fall below 15%
            c) Make-good credits for underperformance
            d) Annual performance review
      `
    },
    
    5: {
      title: 'BILLING & INVOICING',
      content: `
        5.1 Automated Monthly Billing:
            a) Invoice generated by 10th of each month
            b) Payment processed on 15th of month
            c) Detailed savings report provided
            d) Payment receipt sent within 24 hours
        
        5.2 Invoice Contents:
            a) Baseline vs. actual consumption
            b) Weather normalization adjustments
            c) Total verified savings
            d) VibeLux revenue share (30%)
            e) Customer retained savings (70%)
            f) Payment due date
        
        5.3 Payment Terms:
            a) Due upon receipt for automated payments
            b) NET 30 for manual payments
            c) 1.5% monthly late fee after 30 days
            d) Service suspension after 60 days
      `
    },
    
    6: {
      title: 'DISPUTE RESOLUTION',
      content: `
        6.1 Savings Disputes:
            a) Customer may dispute calculations within 30 days
            b) Independent third-party verification available
            c) VibeLux covers verification cost if error > 5%
            d) Adjustments applied to following month
        
        6.2 Billing Disputes:
            a) Submit disputes to billing@vibelux.ai
            b) Response within 5 business days
            c) Payment hold during active dispute
            d) Interest waived on verified errors
        
        6.3 Escalation Process:
            a) Level 1: Customer Success Team
            b) Level 2: Technical Review Board
            c) Level 3: Executive Resolution
            d) Level 4: Binding Arbitration
      `
    },
    
    7: {
      title: 'DATA SECURITY & PRIVACY',
      content: `
        7.1 VibeLux agrees to:
            a) Maintain SOC 2 Type II compliance
            b) Encrypt all payment and utility data
            c) PCI DSS compliance for payment processing
            d) Annual security audits
        
        7.2 Data Usage:
            a) Utility data used solely for savings calculation
            b) Aggregated data may be used for analytics
            c) No sale of customer data to third parties
            d) GDPR and CCPA compliant
        
        7.3 Customer owns all facility and consumption data
      `
    },
    
    8: {
      title: 'TERM & TERMINATION',
      content: `
        8.1 Initial Term: 12 months from activation date
        
        8.2 Automatic Renewal: Month-to-month after initial term
        
        8.3 Termination:
            a) 30 days written notice required
            b) Final reconciliation within 45 days
            c) No early termination fees
            d) Pro-rated final month billing
        
        8.4 VibeLux may terminate for:
            a) Non-payment exceeding 60 days
            b) Failure to provide utility data access
            c) Material breach of agreement
            d) Facility closure or sale
      `
    },
    
    9: {
      title: 'REPRESENTATIONS & WARRANTIES',
      content: `
        9.1 Customer represents:
            a) Authority to enter this agreement
            b) Ownership/lease of facility
            c) Accurate utility account information
            d) Compliance with local regulations
        
        9.2 VibeLux warrants:
            a) Energy savings of at least 15%
            b) Professional service delivery
            c) Accurate savings calculations
            d) Secure data handling
        
        9.3 LIMITATION OF LIABILITY:
            VibeLux's total liability shall not exceed the total fees paid by Customer in the preceding 12 months.
      `
    },
    
    10: {
      title: 'ADDITIONAL PROVISIONS',
      content: `
        10.1 Entire Agreement: This constitutes the entire agreement between parties
        
        10.2 Governing Law: State of California
        
        10.3 Venue: San Francisco County, California
        
        10.4 Severability: Invalid provisions shall not affect remaining terms
        
        10.5 Force Majeure: Neither party liable for acts beyond reasonable control
        
        10.6 Assignment: Customer may not assign without written consent
        
        10.7 Notices: Email to registered addresses constitutes valid notice
      `
    }
  },
  
  consent: {
    required: true,
    checkboxes: [
      {
        id: 'payment_auth',
        label: 'I authorize VibeLux to automatically charge my payment method for 30% of verified energy savings',
        required: true
      },
      {
        id: 'utility_access',
        label: 'I authorize VibeLux to access my utility account data for savings calculation',
        required: true
      },
      {
        id: 'terms_accept',
        label: 'I have read and agree to the Revenue Sharing Terms & Conditions',
        required: true
      },
      {
        id: 'min_guarantee',
        label: 'I understand that I pay nothing if savings are below 15%',
        required: false
      }
    ],
    
    signature: {
      required: true,
      fields: [
        'Full Name',
        'Title',
        'Company',
        'Date',
        'IP Address'
      ]
    }
  },
  
  // Automated acceptance tracking
  acceptance: {
    version: '2.0',
    timestamp: null,
    ipAddress: null,
    userAgent: null,
    checkboxes: {},
    signature: null,
    documentHash: null
  }
};

/**
 * Generate legally binding agreement document
 */
export function generateAgreement(customerData: {
  name: string;
  company: string;
  address: string;
  facilityAddress: string;
  utilityCompany: string;
  accountNumber: string;
  estimatedSavings: number;
}): string {
  let agreement = `
REVENUE SHARING AGREEMENT

This Agreement is entered into as of ${new Date().toLocaleDateString()} between:

VibeLux AI, Inc. ("VibeLux")
1234 Innovation Drive
San Francisco, CA 94105

AND

${customerData.company} ("Customer")
${customerData.address}

FACILITY LOCATION: ${customerData.facilityAddress}
UTILITY PROVIDER: ${customerData.utilityCompany}
ACCOUNT NUMBER: ${customerData.accountNumber}

WHEREAS, VibeLux provides energy optimization services that reduce electricity consumption and costs;
WHEREAS, Customer desires to receive such services on a performance-based revenue sharing model;
WHEREAS, both parties agree to share the economic benefits of energy savings;

NOW, THEREFORE, in consideration of the mutual covenants and agreements contained herein, the parties agree as follows:

`;

  // Add all terms
  for (const [num, section] of Object.entries(REVENUE_SHARING_AGREEMENT.terms)) {
    agreement += `
${section.title}
${section.content}

`;
  }

  agreement += `
ESTIMATED ANNUAL SAVINGS: $${customerData.estimatedSavings.toLocaleString()}
VIBELUX SHARE (30%): $${(customerData.estimatedSavings * 0.30).toLocaleString()}
CUSTOMER RETENTION (70%): $${(customerData.estimatedSavings * 0.70).toLocaleString()}

IN WITNESS WHEREOF, the parties have executed this Agreement as of the date first written above.

VIBELUX AI, INC.                    ${customerData.company.toUpperCase()}

_________________________           _________________________
Authorized Signature                 Authorized Signature

_________________________           _________________________
Print Name                          Print Name

_________________________           _________________________
Title                               Title

_________________________           _________________________
Date                                Date
`;

  return agreement;
}

/**
 * Validate customer acceptance
 */
export function validateAcceptance(acceptance: any): {
  valid: boolean;
  errors: string[];
} {
  const errors: string[] = [];
  
  // Check required checkboxes
  if (!acceptance.checkboxes?.payment_auth) {
    errors.push('Payment authorization must be accepted');
  }
  
  if (!acceptance.checkboxes?.utility_access) {
    errors.push('Utility data access must be authorized');
  }
  
  if (!acceptance.checkboxes?.terms_accept) {
    errors.push('Terms and conditions must be accepted');
  }
  
  // Check signature
  if (!acceptance.signature?.name || !acceptance.signature?.title) {
    errors.push('Valid signature required');
  }
  
  // Check version
  if (acceptance.version !== REVENUE_SHARING_AGREEMENT.version) {
    errors.push('Agreement version mismatch');
  }
  
  return {
    valid: errors.length === 0,
    errors
  };
}